apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: securesync-pro
type: Opaque
data:
  mongodb-root-username: cm9vdA== # root
  mongodb-root-password: UGFzc3dvcmQxMjM= # Password123
  mongodb-username: c2VjdXJlc3luYw== # securesync
  mongodb-password: c2VjdXJlcGFzcw== # securepass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: securesync-pro
data:
  mongodb-url: "mongodb://securesync:securepass@mongodb-service:27017/securesync"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: securesync-pro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: securesync-pro
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-root-password
        - name: MONGO_INITDB_DATABASE
          value: securesync
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        - name: mongodb-config-volume
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
      - name: mongodb-config-volume
        configMap:
          name: mongodb-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  namespace: securesync-pro
data:
  init-mongo.js: |
    db.createUser({
      user: "securesync",
      pwd: "securepass",
      roles: [
        {
          role: "readWrite",
          db: "securesync"
        }
      ]
    });
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: securesync-pro
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
